### ISSUE TITLE
Läxhjälpen Kap 11 - Saknar css-kod

### ISSUE THREAD

**Issue by Isark2** [itpastorn/webbutveckling-1-flex-studentfiles#27]
När man följt kapitel 11 för uppgift 11C så ser inte sidan komplett ut. _Ignorera outlines._
Det nämns angående att header och footer ska vara 100% bredd, men ingen instruktion som visar processen för när man bör göra det. Samt att den första delen för .subpage saknas helt.

Det kan man fixa genom att lägga till följande i css filen:
````css
.subpage {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-wrap: wrap;
      flex-wrap: wrap;
}
.subpage header, .subpage footer {
  -webkit-box-flex: 0;
      -ms-flex: 0 0 100%;
          flex: 0 0 100%;
}
````

**Comment by itpastorn** [comment]
Tack för din feedback

**Comment by itpastorn** [comment]
I mitt "facit" har jag följande regler för body och header och footer som gör samma saker. Det verkar inte framgå av boken.

````css
body {
    margin: auto;
    max-width: 860px;
    font-family: "Helvetica Neue", "Liberation Sans", Calibri, Arial, sans-serif;
    font-size: 100%;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    -webkit-box-pack: justify;
    -ms-flex-pack: justify;
    justify-content: space-between;
}
body > header,
body > footer {
    -webkit-box-flex: 0;
    -ms-flex: 0 0 100%;
    flex: 0 0 100%;
}
````
